Repository merenlab/anvio, pull requests merged in 2020-12, with the labels that each got.

#1570 Restructure COGs module to make room for NCBI's 2020 release
  anvio/__init__.py
  anvio/cogs.py
  anvio/data/interactive/js/constants.js
  anvio/drivers/blast.py
  anvio/filesnpaths.py
  anvio/migrations/contigs/v19_to_v20.py
  anvio/tables/__init__.py
  anvio/terminal.py
  bin/anvi-run-ncbi-cogs
  bin/anvi-setup-ncbi-cogs
Labels: contigs database, design

#1599 Issue 1554 - hmmer multithread fix
  anvio/drivers/hmmer.py
Labels: bug

#1611 Issue 1588: fix --cluster-contigs param in snakemake
  anvio/workflows/metagenomics/Snakefile
Labels: bug

#1607 Metabolism code now works with KEGG snapshot by default
  anvio/__init__.py
  anvio/constants.py
  anvio/data/misc/KEGG-SNAPSHOTS.yaml
  anvio/docs/programs/anvi-estimate-metabolism.md
  anvio/docs/programs/anvi-setup-kegg-kofams.md
  anvio/kegg.py
  bin/anvi-setup-kegg-kofams
Labels: design, documentation

#1500 Generalize enrichment script
  anvio/__init__.py
  anvio/dbops.py
  anvio/docs/__init__.py
  anvio/docs/artifacts/external-genomes.md
  anvio/docs/artifacts/functional-enrichment-txt.md
  anvio/docs/artifacts/groups-txt.md
  anvio/docs/artifacts/internal-genomes.md
  anvio/docs/programs/anvi-compute-functional-enrichment.md
  anvio/docs/programs/anvi-get-enriched-functions-per-pan-group.md
  anvio/genomedescriptions.py
  anvio/kegg.py
  anvio/summarizer.py
  anvio/utils.py
  bin/anvi-compute-functional-enrichment
  bin/anvi-get-enriched-functions-per-pan-group
  sandbox/anvi-script-enrichment-stats
Labels: enhancement
