Repository merenlab/anvio, pull requests merged in 2021-02, with the labels that each got.

#1660 adding aa_seq to external-gene-calls output
  anvio/dbops.py
Labels: feature request

#1659 A lot of improvements to anvi-estimate-metabolism
  anvio/__init__.py
  anvio/docs/programs/anvi-estimate-metabolism.md
  anvio/kegg.py
  bin/anvi-estimate-metabolism
Labels: bug, enhancement, feature

#1672 Reducing stringency of anvi-run-kegg-kofams with a new annotation heuristic
  anvio/__init__.py
  anvio/docs/programs/anvi-run-kegg-kofams.md
  anvio/kegg.py
  anvio/parsers/hmmer.py
  bin/anvi-run-kegg-kofams
Labels: enhancement, metabolism / modules database

#1649 anvi-display-functions
  anvio/__init__.py
  anvio/clustering.py
  anvio/data/interactive/images/functional-bg.png
  anvio/data/interactive/js/main.js
  anvio/dbops.py
  anvio/docs/artifacts/contigs-db.md
  anvio/docs/artifacts/functions.md
  anvio/docs/artifacts/interactive.md
  anvio/docs/images/png/anvi-display-functions-01.png
  anvio/docs/images/png/anvi-display-functions-02.png
  anvio/docs/images/png/anvi-display-functions-03.png
  anvio/docs/programs/anvi-compute-functional-enrichment.md
  anvio/docs/programs/anvi-display-functions.md
  anvio/genomedescriptions.py
  anvio/genomestorage.py
  anvio/interactive.py
  anvio/tables/__init__.py
  bin/anvi-compute-functional-enrichment
  bin/anvi-display-functions
  bin/anvi-display-pan
  sandbox/anvi-script-gen-functions-per-group-stats-output
Labels: core, design, feature, gene functions
