Repository merenlab/anvio, pull requests merged in 2021-03, with the labels that each got.

#1678 Anvi-script-filter-hmm-hits-table
  anvio/__init__.py
  anvio/docs/programs/anvi-run-hmms.md
  anvio/docs/programs/anvi-script-filter-hmm-hits-table.md
  anvio/drivers/hmmer.py
  anvio/interacdome.py
  anvio/parsers/hmmer.py
  anvio/tables/hmmhits.py
  anvio/tests/run_all_tests.sh
  bin/anvi-run-hmms
  sandbox/anvi-script-filter-hmm-hits-table
Labels: feature

#1691 Allow users to specify a temporary directory location with --tmp-dir
  anvio/__init__.py
  anvio/argparse.py
Labels: core

#1690 A script to generate external and internal genomes files
  anvio/__init__.py
  anvio/docs/programs/anvi-script-gen-genomes-file.md
  anvio/utils.py
  sandbox/anvi-script-gen-genomes-file
Labels: enhancement, feature
